# Cargar configuración
bind r source-file $HOME/.tmux.conf

# Numeración del panel
set -g base-index 1
setw -g pane-base-index 1

# Capturar panel
bind-key u capture-pane \; save-buffer ~/tmux-capture

# Barra de estado
set -g status-style "bg=default,fg=default"
set -g status-right '#{host} %d/%m/%y %H:%M'
set -g pane-border-style "fg=brightblack"
