# Temas https://github.com/alacritty/alacritty-theme

[general]
import = [
    "~/.config/alacritty/themes/baitong.toml"
]

[window]
padding = { x = 15, y = 15 }
dynamic_padding = true
opacity = 0.9

[font]
normal = { family = "AnonymicePro Nerd Font", style = "Regular" }
size = 10

[cursor]
style = { shape = "Underline", blinking = "Off"}
